### ISSUE TITLE
Bug and fix to use the Gstreamer pipeline without live video preview

### ISSUE THREAD

**Issue by MatthiasDurrieu** [TheImagingSource/Linux-tiscamera-Programming-Samples#32]
Hello there, 

  I wanted to use the Gstreamer pipeline defined in **TIS.py** with '**showvideo**' set to 'false' which consistently returned the following error: 

_AttributeError: 'NoneType' object has no attribute 'get_buffer'_

Changing the pipeline string in line 84 from "p += f' ! {conversion} appsink name=sink'" to "p += f" ! queue ! {conversion} appsink name=sink" fixed the issue for me. 

I'm sharing this here in case that helps.
Cheers

**Comment by TIS-Stefan** [comment]
Hello Matthias

Thank you for letting me know. I did not knew, that there is a difference between ' and ". I changed that in the TIS.py file.

Stefan

**Comment by MatthiasDurrieu** [comment]
Hi,

  Thank you for you reply! However my comment was about adding "! queue " before ! "{conversion} appsink name=sink" in the line 84 where pipeline definition when showvideo is set to False is declared, not about the ' vs " which should not make a difference unless you need nested "" statements.

Best,

Matthias

**Comment by TIS-Stefan** [comment]
Hello Matthias

the queue is not necessary, because we do not use a tee element, if we do not show the live video stream.  The pipeline from

```Python
 p = 'tcambin name=source ! capsfilter name=caps'
 p += f" ! {conversion} appsink name=sink"
```
results in 

tcambin name=source ! capsfilter name=caps ! appsink name=sink

There is no queue element necessary in order to create a new thread. However, I faintly remember having this error some time ago, but I do not remember, what caused it. Somehow sample must be None, thus you get the error message. 
You could try to add "sync=false"
```Python
 p += f" ! {conversion} appsink name=sink sync=false"
```
Or simply stay with the queue element. It creates a copy of the buffer coming from tcambin and forwards it to the appsink. 

Stefan
