### ISSUE TITLE
How to control the gain and the shutter speed

### ISSUE THREAD

**Issue by tkym525** [TheImagingSource/Linux-tiscamera-Programming-Samples#4]
Hi
I use "Save an image using OpenCV in C++" with DMK27BUR0135 and I want to change the gain and the shutter speed that are auto mode now.
Please tell me How to control the gain and the shutter speed.

**Comment by davidsean** [comment]
Have you tried looking at changing the properties? Take a look at the example under `Linux-tiscamera-Programming-Samples/Using Properties in C++/`

You can print the `gain` and try to change it to see if it works, but before you may want to set 
 `gain auto` (or whatever the name of the property for automatic gain is) to `false` so that it doesn't re-adjust by itself.
The shutter speed can probably be controlled using the `Exposure` property (I think it's the exposure time in units of 100ns). Your camera may have the `Exposure Time (us)` property which is more explicit is what it represents.

I would try first by listing all available properties to see which ones you can change and work from there.
